--USERS table
CREATE TABLE USERS (
    user_id   NUMBER(8)    PRIMARY KEY,
    user_name VARCHAR2(20) NOT NULL,
    user_pass VARCHAR2(20) NOT NULL
);

--THREADS table
CREATE TABLE THREADS (
    thread_id    NUMBER(8)    PRIMARY KEY,
    thread_title VARCHAR2(100) NOT NULL
);

--POSTS table
CREATE TABLE POSTS (
    post_id      NUMBER(12)   PRIMARY KEY,
    thread_id    NUMBER(8)    REFERENCES THREADS(thread_id),
    user_id      NUMBER(8)    REFERENCES USERS(user_id),
    post_number  NUMBER(3)    NOT NULL,
    post_content VARCHAR2(400) NOT NULL,
    post_date    DATE DEFAULT SYSDATE
);

--COMMENTS table
CREATE TABLE COMMENTS (
    comment_id   NUMBER(12)   PRIMARY KEY,
    post_id      NUMBER(12)   NOT NULL,
    user_id      NUMBER(8)    NOT NULL,
    content      VARCHAR2(400) NOT NULL,
    comment_date DATE DEFAULT SYSDATE,
    CONSTRAINT fk_comments_posts FOREIGN KEY (post_id) REFERENCES POSTS(post_id),
    CONSTRAINT fk_comments_users FOREIGN KEY (user_id) REFERENCES USERS(user_id)
);


--Sequences
CREATE SEQUENCE SEQ_USERS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_THREADS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_POSTS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_COMMENTS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
